server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/cloud?useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.pxl.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#  logback:
#    rollingpolicy:
#      max-file-size: 10KB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log