server:
  port: 8001
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/cloud?useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    sentinel:
      web-context-unify: false # 关闭context整合，如果不关闭，簇点链路 中 流控模式-链路 显示就会有问题。
      transport:
        dashboard: 10.211.55.5:8090
    nacos:
      server-addr: 192.168.0.103:8843
#      server-addr: 10.211.55.5:80
      discovery:
        #集群名称，多个服务属于同一个集群时，优先访问集群内部服务。
        cluster-name: HN
        # 命名空间，填ID，该ID在Nacos服务器命名空间中有显示。
#        namespace: 1966b244-aa55-41e7-abc3-c1a96db2fcf7
mybatis:
  type-aliases-package: cn.pxl.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
#  level:
#    root: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#  logback:
#    rollingpolicy:
#      max-file-size: 10KB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.0.103:10086/eureka

feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持，微服务远程调用都是基于Feign来完成的，因此我们需要将Feign与Sentinel整合，在Feign里面实现线程隔离和服务熔断。
  client:
    config:
      # 包含四种不同的级别：NONE、BASIC、HEADERS、FULL
      # 针对某个微服务的配置
      userservice:
        # 日志级别
        loggerLevel: HEADERS
      # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
      default:
        # 日志级别尽量用basic
        loggerLevel: BASIC
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数