server:
  port: 8011
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/cloud?useSSL=false
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
#      server-addr: 10.211.55.5:80
      server-addr: localhost:8843
      discovery:
        #集群名称，多个服务属于同一个集群
        cluster-name: HN
        # 命名空间，填ID，该ID在Nacos服务器命名空间中有显示。不同的名称空间的服务彼此不可见。
#        namespace: 1966b244-aa55-41e7-abc3-c1a96db2fcf7
        # 设置为非临时实例（永久实例）
#        ephemeral: false

mybatis:
  type-aliases-package: cn.pxl.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.0.103:10086/eureka

